// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SassoInmobiliariaAPI.Data.Services;

#nullable disable

namespace SassoInmobiliariaAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241217202736_newColumnStateOfDevelop")]
    partial class newColumnStateOfDevelop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SassoInmobiliariaAPI.Models.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SassoInmobiliariaAPI.Models.Entities.DevelopmentProp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DevelopAdress")
                        .HasColumnType("longtext");

                    b.Property<string>("DevelopDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("DevelopImage")
                        .HasColumnType("longtext");

                    b.Property<string>("DevelopName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StateOfDevelop")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentProps");
                });

            modelBuilder.Entity("SassoInmobiliariaAPI.Models.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("longtext");

                    b.Property<float>("Area")
                        .HasColumnType("float");

                    b.Property<int>("Baths")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DevelopmentPropId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDistingued")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUpToCredit")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Latitude")
                        .HasColumnType("float");

                    b.Property<float>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("StateOfDevelop")
                        .HasColumnType("int");

                    b.Property<int?>("TypeOfOffer")
                        .HasColumnType("int");

                    b.Property<int?>("TypeOfProp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentPropId");

                    b.ToTable("Propertys");
                });

            modelBuilder.Entity("SassoInmobiliariaAPI.Models.Entities.Property", b =>
                {
                    b.HasOne("SassoInmobiliariaAPI.Models.Entities.DevelopmentProp", null)
                        .WithMany("Properties")
                        .HasForeignKey("DevelopmentPropId");
                });

            modelBuilder.Entity("SassoInmobiliariaAPI.Models.Entities.DevelopmentProp", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
